# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e48a04435800a01ecb6c04d21c5c7b0fcb0352bc20e3110b79bd315472dbba452e95a0df50a59028cd973e986590129fbff756ec90fff8c1b5a53ab13d38aa80

test:
  secret_key_base: 454c49505dfc7567ebed72ac1caa010103df66a7b1171e5ce36a5983151d3e38fdd19737ab4507da1c1a5bb5efd52bef148a8334c0466e76ce576a47ca5a8948

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
